const REGISTER_ACTIONS = {
    REGISTER_CUSTOMER_INFO: 'REGISTER_CUSTOMER_INFO',
    ADD_CUSTOMER_SUCCESS: 'ADD_CUSTOMER_SUCCESS',
    ACTION_CUSTOMER_FAILURE:'ACTION_CUSTOMER_FAILURE',
}

export default REGISTER_ACTIONS