const CATEGORY_ACTIONS = {
    ACTION_CATEGORIES_REQUEST: 'ACTION_CATEGORIES_REQUEST',
    ACTION_CATEGORIES_FAILURE: 'ACTION_CATEGORIES_FAILURE',
    FETCH_ALL_CATEGORIES_SUCCESS: 'FETCH_ALL_CATEGORIES_SUCCESS',
    FETCH_A_CATEGORY_BY_NAME: 'FETCH_A_CATEGORY_BY_NAME'
}

export default CATEGORY_ACTIONS