const LOGIN_ACTIONS = {
    LOGIN_CUSTOMER_INFO:'LOGIN_CUSTOMER_INFO',
    ACTION_LOGIN_SUCCESS:'ACTION_LOGIN_SUCCESS',
    ACTION_LOGIN_FAILURE:'ACTION_LOGIN_FAILURE',
    ACTION_LOGIN_GOOGLE:'ACTION_LOGIN_GOOGLE',
    ACTION_GET_CREDENTIALS:'ACTION_GET_CREDENTIALS',


}

export default LOGIN_ACTIONS