const LOGIN_ACTIONS = {
    LOGIN_CUSTOMER_INFO:'LOGIN_CUSTOMER_INFO',
    ACTION_LOGIN_SUCCESS:'ACTION_LOGIN_SUCCESS',
    ACTION_LOGIN_FAILURE:'ACTION_LOGIN_FAILURE'

}

export default LOGIN_ACTIONS