const VERIFY_ACTIONS = {
    ACTION_TOKEN_REQUEST: 'ACTION_VERIFY_REQUEST',
    ACTION_VERIFY_FAILURE: 'ACTION_VERIFY_FAILURE',
    FETCH_TOKEN_SUCCESS: 'FETCH_TOKEN_SUCCESS',
    PERMISSION_REQUEST: 'PERMISSION_REQUEST',
    PERMISSION_SUCCES: 'PERMISSION_SUCCES',
    PERMISSION_FAILURE: 'PERMISSION_FAILURE'
}

export default VERIFY_ACTIONS